// Autogenerated from file stdlib/2-append.lsp DO NOT TOUCH
doString(&vm,
"(define append\n"
"  (lambda args\n"
"    (let append-inner\n"
"      (lambda (lst lsts)\n"
"        (if (null? lst)\n"
"            (if (null? lsts)\n"
"                '()\n"
"                (append-inner (car lsts) (cdr lsts)))\n"
"            (cons (car lst)\n"
"                  (append-inner (cdr lst) lsts)))))\n"
"    (if (and (not (null? args))\n"
"             (not (list? (car args))))\n"
"        (car args)\n"
"        (append-inner '() args))))\n"
"",
0, false, "stdlib/2-append.lsp");