// Autogenerated from file stdlib/4-quasiquote.lsp DO NOT TOUCH
doString(&vm,
";; See 3-quasiquote-helpers.lsp\n"
"\n"
"(defmacro quasiquote (arg)\n"
"  (qq-expand arg))\n"
"",
0, false, "stdlib/4-quasiquote.lsp");