// Autogenerated from file stdlib/5-for.lsp DO NOT TOUCH
doString(&vm,
"(defmacro for (init . body)\n"
"  (let iter (gensym))\n"
"  (let for-label (gensym))\n"
"  `(scope\n"
"    (let ,iter ,(car (cdr init)))\n"
"    (label ,for-label)\n"
"    (if (get-slot ,iter 'alive)\n"
"        (scope\n"
"         (let ,(car init) ((get-slot ,iter 'update) ,iter))\n"
"         ,@body\n"
"         (go ,for-label)))))\n"
"",
0, false, "stdlib/5-for.lsp");