// Autogenerated from file stdlib/6-error-handling.lsp DO NOT TOUCH
doString(&vm,
";; Change to a Cpp function, and make error! automagically do this stuff\n"
";(define stack-trace ()\n"
"  ;(let ret '())\n"
"  ;(for (stack-index (reverse-range (- (stack-depth) 1) 1))\n"
"       ;(set! ret (cons (stack-info stack-index) ret)))\n"
"  ;ret)\n"
"\n"
";; Define in Cpp when we handle Cpp defined macros\n"
"(defmacro error! args\n"
"  `(scope\n"
"    (crash! (list ,@args))))\n"
"\n"
"(defmacro assert! (pred . msg)\n"
"  `(if (not ,pred)\n"
"       (error! \"assert \" ',pred \" failed\" (newline) ,@msg)))\n"
"",
0, false, "stdlib/6-error-handling.lsp");