// Autogenerated from file stdlib/7-car-abr.lsp DO NOT TOUCH
doString(&vm,
"(defmacro cadr (lst)\n"
"  `(car (cdr ,lst)))\n"
"\n"
"(defmacro caar (lst)\n"
"  `(car (car ,lst)))\n"
"\n"
"(defmacro cadar (lst)\n"
"  `(cadr (car ,lst)))\n"
"\n"
"(defmacro cdar (lst)\n"
"  `(cdr (car ,lst)))\n"
"\n"
"(defmacro caddar (lst)\n"
"  `(cadr (cdar ,lst)))\n"
"\n"
"(defmacro caaar (lst)\n"
"  `(car (caar ,lst)))\n"
"\n"
"(defmacro cadaar (lst)\n"
"  `(cadr (caar lst)))\n"
"",
0, false, "stdlib/7-car-abr.lsp");