// Autogenerated from file stdlib/7-print-stack-trace.lsp DO NOT TOUCH
doString(&vm,
";(define print-stack-trace (trace)\n"
"  ;(let inner (trace level)\n"
"       ;(if (not (null? trace))\n"
"           ;(scope\n"
"            ;(let proc-name (caar trace))\n"
"            ;(let file-name (cadar trace))\n"
"            ;(let call-line (as-int (caddar trace)))\n"
"            ;(let def-line (as-int (cadddar trace)))\n"
"            ;(println! \"#\" (as-int level) \" \"\n"
"                      ;proc-name \" at \"\n"
"                      ;file-name \":\"\n"
"                      ;call-line)\n"
"            ;(inner (cdr trace) (+ level 1)))))\n"
"  ;(println! \"STACK-TRACE:\")\n"
"  ;(inner trace 0))\n"
"",
0, false, "stdlib/7-print-stack-trace.lsp");