// Autogenerated from file stdlib/8-list-iterator.lsp DO NOT TOUCH
doString(&vm,
"(define list-iterator (lst)\n"
"  {(curr lst) (alive (not (null? lst)))\n"
"   (update (lambda (this)\n"
"             (let ret '())\n"
"             (if (get-slot this 'alive)\n"
"                 (scope\n"
"                  (set! ret (car (get-slot this 'curr)))\n"
"                  (set-slot! this 'curr (cdr (get-slot this 'curr)))\n"
"                  (if (null? (get-slot this 'curr))\n"
"                      (set-slot! this 'alive false))))\n"
"             ret))})\n"
"",
0, false, "stdlib/8-list-iterator.lsp");