import argparse
parser = argparse.ArgumentParser()
parser.add_argument("src", help="The file to read from")
parser.add_argument("dst", help="The file to write to")
args = parser.parse_args()
with open(args.src, "r") as src, open(args.dst, "w") as dst:
    dst.write("// Autogenerated from file ")
    dst.write(args.src)
    dst.write(" DO NOT TOUCH\n")
    dst.write("doString(&vm,\n\"")
    line = src.readline()
    while line:
        dst.write(line.replace('\n', '').replace("\"", "\\\""))
        dst.write("\\n\"\n\"")
        line = src.readline()
    #dst.write(src.read().replace('\n', '\\n'))
    dst.write("\",\nfalse, \"")
    dst.write(args.src)
    dst.write("\");")