import argparse
parser = argparse.ArgumentParser()
parser.add_argument("dst", help="The destination file")
parser.add_argument("files", help="The files making up the stdlib",
                    nargs="+")
args = parser.parse_args()

with open(args.dst, "w") as dst:
    dst.write("// Autogenerated from the files in stdlib. DO NOT TOUCH\n")
    for f in args.files:
        dst.write("#include \"")
        dst.write(f)
        dst.write("\"\n")
